name: Test Python

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Populate .env with additional vars
        run: |
          cp ./.github/.github.env .env
          echo "AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "TWINE_USERNAME=${{ secrets.TWINE_USERNAME_TEST }}" >> .env
          echo "TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD_TEST }}" >> .env
          echo "TWINE_NON_INTERACTIVE=${{ secrets.TWINE_NON_INTERACTIVE }}" >> .env

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup python environment
        run: |
          make venv

      - name: Test
        run: |
          source .venv/bin/activate && pytest

      - name: Deploy to test PyPi
        run: |
          make deploy/test
